FROM jenkins/jenkins:lts

# устанавливаем docker-cli, jq
USER root
RUN apt-get update && apt-get install -y docker.io && apt-get install -y jq
USER jenkins

# установка плагинов
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt

# Wizard не нужен
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

COPY casc.yml /var/jenkins_home/casc.yml
COPY jobs.groovy /var/jenkins_home/jobs.groovy
